### ISSUE TITLE
Cannot overwrite background on sections via child-theme (!important used in parent)

### ISSUE THREAD

**Issue by mclaurent** [mtomas7/tiny-framework#2]
Hi

Any chance we could remove the !important use on .content-area section. The reason appears to be a line removing the background-image using !important, so I cannot overwrite it in my child-theme (without using !important). Since we never set a background on .content-area section in the child theme, could we just change the definition so that we only reset the background on the .content-area article (as that is the only one actually having a background set (see public_html/wp-content/themes/tiny-framework/style.css:2361). 
VisualComposer is using the <section element, but I cannot set a background on them because the parent theme overwrites them.

Could we change the styling so that we do not unset the background on sections but only do it on articles?

So in style.css:2348, change
````
/* Remove content bottom border for a single page, attachement page and for the last post in archive view listing */
.attachment .content-area article,
.content-area article:last-child,
.content-area section, /* section is for 404.php and content-none.php */
.page .content-area article {
	background-image: none!important;
	border-bottom: 0;
	margin-bottom: 24px;
	margin-bottom: 1.5rem;
}
````
to
````
/* Remove content bottom border for a single page, attachement page and for the last post in archive view listing */
.attachment .content-area article,
.content-area article:last-child,
.content-area section, /* section is for 404.php and content-none.php */
.page .content-area article {
	border-bottom: 0;
	margin-bottom: 24px;
	margin-bottom: 1.5rem;
}
/* Remove the background on articles in the main content area. */
.attachment .content-area article,
.content-area article:last-child,
.page .content-area article {
	background-image: none!important;
}
````
Cheers

**Comment by mtomas7** [comment]
Thank you for the contribution!

Currently I'm working on other projects, but after the release of WP 5.0, when Gutenberg editor will have more stable build, I will try to dedicate time to renew theme.
